export const COMMENTS_LOADING = "COMMENTS_LOADING"
export const COMMENTS_FAILED = "COMMENTS_FAILED"
export const ADD_COMMENTS = "ADD_COMMENTS"

export const ADD_COMMENT = "ADD_COMMENT"
export const POST_COMMENT = "POST_COMMENT"
export const DELETE_COMMENT = "DELETE_COMMENT"
// export const LOAD_RECIPE = "LOAD_RECIPE"