export const RECIPES_LOADING = "RECIPES_LOADING"
export const RECIPES_FAILED = "RECIPES_FAILED"
export const ADD_RECIPES = "ADD_RECIPES"

// FOR THE LANDING PAGE FILTERING
export const ADD_FILTERED_RECIPES = "ADD_FILTERED_RECIPES"
export const CHANGE_COURSE = "CHANGE_COURSE"

export const ADD_CUISINES = "ADD_CUISINES"
export const REMOVE_CUISINES = "REMOVE_CUISINES"

export const ADD_INGREDIENTS = "ADD_INGREDIENTS"
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS"

export const UPDATE_DIFFICULTY = "UPDATE_DIFFICULTY"
export const UPDATE_COOKTIME = "UPDATE_COOKTIME"
export const UPDATE_COURSE = "UPDATE_COURSE"
export const UPDATE_SORT = "UPDATE_SORT"
export const RECIPES_LOADING_FILTERS = "RECIPES_LOADING_FILTERS"

export const ADD_RECIPE = "ADD_RECIPE"
export const EDIT_RECIPE = "EDIT_RECIPE"
export const DELETE_RECIPE = "DELETE_RECIPE"
export const LOAD_RECIPE = "LOAD_RECIPE"
